### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by githubcdr** [keel-hq/keel#282]
Hi,

Are there any plans to support Keel on ARM machines?

**Comment by rusenask** [comment]
hi, there is no reason not to :) armhf and aarch64?

**Comment by githubcdr** [comment]
I run a lab on raspberry so armhf would be nice :)

**Comment by rusenask** [comment]
okay, will try to get to this when I have a minute. Ideally docker cloud should build it, otherwise maybe circle CI could be also used for this.

**Comment by githubcdr** [comment]
nice, I will test as soon it lands

**Comment by rusenask** [comment]
Hi @githubcdr, added makefile scripts to build it. Currently also used upx to make them smaller, built armhf and aarch64:

https://hub.docker.com/r/keelhq/keel-arm/tags/

Will think of a way to automate builds, maybe with cloudbuild since docker cloud would take ages to compress.

**Comment by githubcdr** [comment]
Hi @rusenask,

I noticed this error when starting the -arm tagged image on raspberry;

```
Error: failed to start container "keel": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/bin/keel\": stat /bin/keel: no such file or directory": unknown
Back-off restarting failed container
```

image itself seems to be running, will check some more...

```
sudo docker run -it keelhq/keel-arm --help
INFO[0000] extension.credentialshelper: helper registered  name=aws
INFO[0000] bot: registered                               name=slack
usage: keel [<flags>]

Automated Kubernetes deployment updates. Learn more on https://keel.sh.

Flags:
  --help       Show context-sensitive help (also try --help-long and --help-man).
  --incluster  use in cluster configuration (defaults to 'true'), use '--no-incluster' if running outside of the cluster
  --kubeconfig="/root/.kube/config"
               path to kubeconfig (if not in running inside a cluster)
  --version    Show application version.
```

**Comment by rusenask** [comment]
Hi @githubcdr, I think deployment defines command as well, I will just change images to have the same target.

**Comment by githubcdr** [comment]
And while you''re at it release a version tagged image ;)

**Comment by rusenask** [comment]
Done, please test it :)

**Comment by githubcdr** [comment]
Getting there, the image runs but with errors;

```
time="2018-10-07T19:10:13Z" level=info msg="extension.credentialshelper: helper registered" name=aws
time="2018-10-07T19:10:13Z" level=info msg="bot: registered" name=slack
time="2018-10-07T19:10:13Z" level=info msg="keel starting..." arch=arm build_date=2018-10-07T190104Z go_version=go1.10.3 os=linux revision=f571b82c version=0.11.2
time="2018-10-07T19:10:13Z" level=info msg="provider.kubernetes: using in-cluster configuration"
time="2018-10-07T19:10:13Z" level=info msg="provider.defaultProviders: provider 'kubernetes' registered"
time="2018-10-07T19:10:13Z" level=info msg="extension.credentialshelper: helper registered" name=secrets
time="2018-10-07T19:10:13Z" level=info msg="bot.slack.Configure(): Slack approval bot is not configured"
time="2018-10-07T19:10:13Z" level=error msg="bot.Run(): can not get configuration for bot [slack]"
time="2018-10-07T19:10:13Z" level=info msg="trigger.poll.manager: polling trigger configured"
time="2018-10-07T19:10:13Z" level=info msg="webhook trigger server starting..." port=9300
time="2018-10-07T19:10:13Z" level=info msg=started context=watch resource=statefulsets
time="2018-10-07T19:10:13Z" level=info msg=started context=buffer
time="2018-10-07T19:10:13Z" level=info msg=started context=watch resource=daemonsets
time="2018-10-07T19:10:13Z" level=info msg=started context=watch resource=cronjobs
time="2018-10-07T19:10:13Z" level=info msg=started context=watch resource=deployments
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x1156c]
 goroutine 51 [running]:
sync/atomic.addUint64(0x12db2c4c, 0x1, 0x0, 0x12a9e01c, 0x0)
	/usr/local/go/src/sync/atomic/64bit_arm.go:31 +0x4c
github.com/keel-hq/keel/approvals.(*DefaultManager).SubscribeApproved(0x12db2c40, 0xf446f0, 0x12ddc040, 0x12ddc040, 0x12d7a000, 0x0)
	/home/karolis/go/src/github.com/keel-hq/keel/approvals/approvals.go:171 +0x40
github.com/keel-hq/keel/provider.(*DefaultProviders).subscribeToApproved(0x12befb50)
	/home/karolis/go/src/github.com/keel-hq/keel/provider/provider.go:60 +0x70
created by github.com/keel-hq/keel/provider.New
	/home/karolis/go/src/github.com/keel-hq/keel/provider/provider.go:45 +0x1d4
```

**Comment by rusenask** [comment]
oh great :| did some changes, another image with the same tag should be there in a few minutes, if it works, I will commit changes.

**Comment by githubcdr** [comment]
Looks good now!

**Comment by JavierPYA** [comment]
@rusenask keel-arm look unmaintained, is it planned to build arm images again?

**Comment by czyrok** [comment]
+1

**Comment by Forcebyte** [comment]
Hey all

I saw the same build issue with a local lab I am running, and proposed this PR to fix it: https://github.com/keel-hq/keel/pull/830 - I am cross-posting on other issues just in case anyone else has this same issue

### What this PR does

This adds underlying multi-arch support to allow for ARM images to be built and distribution by ghcr.io (the Github image official repository)

### I want to test or use this in the interim

I have added a weekly trigger (for now) that can be changed that will rebuild the arm image from latest weekly - just in case someone wants to run this locally or if this doesn't get merged for other reasons

It can be found here: https://github.com/Forcebyte/keel-arm/pkgs/container/keel-arm
```
docker pull ghcr.io/forcebyte/keel-arm:latest
```
