### ISSUE TITLE
ARM error & update

### ISSUE THREAD

**Issue by zjael** [keel-hq/keel#388]
Running the example deployment, pointed to the keelhq/keel-arm image gives me this error:

```
time="2019-05-09T15:07:05Z" level=info msg="extension.credentialshelper: helper registered" name=aws
time="2019-05-09T15:07:05Z" level=info msg="bot: registered" name=slack
time="2019-05-09T15:07:05Z" level=info msg="keel starting..." arch=arm build_date=2018-10-07T190104Z go_version=go1.10.3 os=linux revision=f571b82c version=0.11.2
time="2019-05-09T15:07:05Z" level=info msg="provider.kubernetes: using in-cluster configuration"
time="2019-05-09T15:07:05Z" level=info msg="provider.defaultProviders: provider 'kubernetes' registered"
time="2019-05-09T15:07:05Z" level=info msg="extension.credentialshelper: helper registered" name=secrets
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x1156c]

goroutine 27 [running]:
sync/atomic.addUint64(0x138ac40c, 0x1, 0x0, 0x1359e01c, 0x0)
        /usr/local/go/src/sync/atomic/64bit_arm.go:31 +0x4c
github.com/keel-hq/keel/approvals.(*DefaultManager).SubscribeApproved(0x138ac400, 0xf446f0, 0x13882080, 0x13882080, 0x13962008, 0xc13532)
        /home/karolis/go/src/github.com/keel-hq/keel/approvals/approvals.go:171 +0x40
github.com/keel-hq/keel/provider.(*DefaultProviders).subscribeToApproved(0x13653930)
        /home/karolis/go/src/github.com/keel-hq/keel/provider/provider.go:60 +0x70
created by github.com/keel-hq/keel/provider.New
        /home/karolis/go/src/github.com/keel-hq/keel/provider/provider.go:45 +0x1d4
```

Aswell it would be awesome to have the arm image at the latest version of keel. :)

**Comment by rusenask** [comment]
Hi, oops :) Just pushed to 0.14.2 arm tags. Since we moved to drone builder from docker cloud, I will finally automate arm image builds so it's not forgotten anymore.

**Comment by zjael** [comment]
Awesome, runs smoothly now aswell. :+1:
