### ISSUE TITLE
Potential issue with helm interface

### ISSUE THREAD

**Issue by rusenask** [keel-hq/keel#392]
During chart tests keel got a panic https://circleci.com/gh/keel-hq/keel/751?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1090974]

goroutine 39 [running]:
github.com/keel-hq/keel/provider/helm.(*Provider).TrackedImages(0xc00041fe00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/keel-hq/keel/provider/helm/helm.go:179 +0x74
github.com/keel-hq/keel/provider.(*DefaultProviders).TrackedImages(0xc0003ea980, 0x0, 0x0, 0xb0, 0x5e, 0x0)
	/go/src/github.com/keel-hq/keel/provider/provider.go:100 +0x105
github.com/keel-hq/keel/trigger/poll.(*DefaultManager).scan(0xc00041fe40, 0x18697e0, 0xc00041ea40, 0x1, 0x5)
	/go/src/github.com/keel-hq/keel/trigger/poll/manager.go:74 +0x4b
github.com/keel-hq/keel/trigger/poll.(*DefaultManager).Start(0xc00041fe40, 0x18697e0, 0xc00041ea40, 0x0, 0x0)
	/go/src/github.com/keel-hq/keel/trigger/poll/manager.go:48 +0xdf
created by main.setupTriggers
	/go/src/github.com/keel-hq/keel/cmd/keel/main.go:316 +0x46a
```

Code in question here:

```golang
// TrackedImages - returns tracked images from all releases that have keel configuration
func (p *Provider) TrackedImages() ([]*types.TrackedImage, error) {
	var trackedImages []*types.TrackedImage

	releaseList, err := p.implementer.ListReleases()
	if err != nil {
		return nil, err
	}

	for _, release := range releaseList.Releases {  // <-- here's line 179
		// getting configuration
```

Could it be that helm returned a nil error but nil response too? :/

**Comment by rusenask** [comment]
fixed https://github.com/keel-hq/keel/pull/404
