### ISSUE TITLE
Polling issue with helm provider

### ISSUE THREAD

**Issue by rusenask** [keel-hq/keel#453]
For some reason user is seeing this https://kubernetes.slack.com/archives/C6JDWE7M2/p1570114712011300?thread_ts=1570108051.007500&cid=C6JDWE7M2. 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x15acf77]

goroutine 124 [running]:
github.com/keel-hq/keel/trigger/poll.(*RepositoryWatcher).addJob(0xc000948ae0, 0xc0008a05a0, 0xc002a3ed60, 0xa, 0x371f580, 0xc000a17c00)
    /go/src/github.com/keel-hq/keel/trigger/poll/watcher.go:234 +0x257
github.com/keel-hq/keel/trigger/poll.(*RepositoryWatcher).watch(0xc000948ae0, 0xc0008a05a0, 0xc0002997a0, 0x0, 0x0, 0x0)
    /go/src/github.com/keel-hq/keel/trigger/poll/watcher.go:192 +0xa3b
github.com/keel-hq/keel/trigger/poll.(*RepositoryWatcher).Watch(0xc000948ae0, 0xc00097fb00, 0x3, 0x4, 0x0, 0x0)
    /go/src/github.com/keel-hq/keel/trigger/poll/watcher.go:134 +0xf2
github.com/keel-hq/keel/trigger/poll.(*DefaultManager).scan(0xc0007417c0, 0x20fb020, 0xc000845840, 0x1, 0x1)
    /go/src/github.com/keel-hq/keel/trigger/poll/manager.go:79 +0x78
github.com/keel-hq/keel/trigger/poll.(*DefaultManager).Start(0xc0007417c0, 0x20fb020, 0xc000845840, 0x0, 0x0)
    /go/src/github.com/keel-hq/keel/trigger/poll/manager.go:48 +0xf4
created by main.setupTriggers
    /go/src/github.com/keel-hq/keel/cmd/keel/main.go:423 +0x6ee
```

Need to refactor that part to have proper error handling

**Comment by amq** [comment]
Also started seeing this, since `0.16.0`. While `0.15.1` runs fine.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1556a85]

goroutine 62 [running]:
github.com/keel-hq/keel/trigger/poll.(*RepositoryWatcher).addJob(0xc000768cf0, 0xc000b80480, 0xc000ed72d0, 0x9, 0x31d3a60, 0xc000dbf900)
        /go/src/github.com/keel-hq/keel/trigger/poll/watcher.go:234 +0x255
github.com/keel-hq/keel/trigger/poll.(*RepositoryWatcher).watch(0xc000768cf0, 0xc000b80480, 0x0, 0x0, 0x4000106, 0x0)
        /go/src/github.com/keel-hq/keel/trigger/poll/watcher.go:192 +0x8de
github.com/keel-hq/keel/trigger/poll.(*RepositoryWatcher).Watch(0xc000768cf0, 0xc000e22b20, 0x3, 0x4, 0x0, 0x0)
        /go/src/github.com/keel-hq/keel/trigger/poll/watcher.go:134 +0xf2
github.com/keel-hq/keel/trigger/poll.(*DefaultManager).scan(0xc000573fc0, 0x208da60, 0xc000572d00, 0x1, 0x1)
        /go/src/github.com/keel-hq/keel/trigger/poll/manager.go:79 +0x78
github.com/keel-hq/keel/trigger/poll.(*DefaultManager).Start(0xc000573fc0, 0x208da60, 0xc000572d00, 0x0, 0x0)
        /go/src/github.com/keel-hq/keel/trigger/poll/manager.go:48 +0xf2
created by main.setupTriggers
        /go/src/github.com/keel-hq/keel/cmd/keel/main.go:436 +0x6ed
```

Chart `0.8.16`

Install command:
```
helm upgrade -i keel keel/keel --namespace=kube-system \
    --set gcr.enabled=true \
    --set gcr.projectId=$PROJECT \
    --set gcr.pubsub.enabled=true \
    --set gcr.clusterName=$PROJECT-$CLUSTER \
    --set secret.name=keel-google \
    --set secret.create=false \
    --set googleApplicationCredentials=notused
```

**Comment by maksimru** [comment]
could be related to #501

**Comment by vinfry** [comment]
Hi,

Unfortunately, the new release still has this issue:

`
time="2020-06-09T13:53:23Z" level=info msg=started context=buffer
time="2020-06-09T13:53:23Z" level=info msg=started context=watch resource=deployments
time="2020-06-09T13:53:23Z" level=info msg=started context=watch resource=statefulsets
time="2020-06-09T13:53:23Z" level=info msg=started context=watch resource=daemonsets
time="2020-06-09T13:53:23Z" level=info msg=started context=watch resource=cronjobs
time="2020-06-09T13:53:24Z" level=debug msg="provider.helm: failed to get config for release" error="policy not specified" namespace=default release=nginx-ingress
time="2020-06-09T13:53:24Z" level=debug msg="extension.credentialshelper: helper doesn't support this registry" error="unsupported registry" helper=aws tracked_image="namespace:kube-system,image:index.docker.io/keelhq/keel:latest,provider:helm,trigger:poll,sched:@every 3m,secrets:[]"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1556a85]

goroutine 43 [running]:
github.com/keel-hq/keel/trigger/poll.(*RepositoryWatcher).addJob(0xc000482fc0, 0xc000401b90, 0xc000bc4270, 0x9, 0x31d3a60, 0xc000c96600)
        /go/src/github.com/keel-hq/keel/trigger/poll/watcher.go:234 +0x255
github.com/keel-hq/keel/trigger/poll.(*RepositoryWatcher).watch(0xc000482fc0, 0xc000401b90, 0x0, 0x0, 0x3000107, 0x0)
        /go/src/github.com/keel-hq/keel/trigger/poll/watcher.go:192 +0x8de
github.com/keel-hq/keel/trigger/poll.(*RepositoryWatcher).Watch(0xc000482fc0, 0xc000ca93b0, 0x2, 0x2, 0x0, 0x0)
        /go/src/github.com/keel-hq/keel/trigger/poll/watcher.go:134 +0xf2
github.com/keel-hq/keel/trigger/poll.(*DefaultManager).scan(0xc0006f0300, 0x208da60, 0xc0004462c0, 0x1, 0x1)
        /go/src/github.com/keel-hq/keel/trigger/poll/manager.go:79 +0x78
github.com/keel-hq/keel/trigger/poll.(*DefaultManager).Start(0xc0006f0300, 0x208da60, 0xc0004462c0, 0x0, 0x0)
        /go/src/github.com/keel-hq/keel/trigger/poll/manager.go:48 +0xf2
created by main.setupTriggers
        /go/src/github.com/keel-hq/keel/cmd/keel/main.go:436 +0x6ed
`

**Comment by rusenask** [comment]
ah, that seems helm part, need to check that one

**Comment by hlubek** [comment]
I also noticed a panic when adding a `poll` trigger with an image in a private registry without matching credentials. #519 should at least fix the panic and output a more meaningful log entry.

**Comment by rusenask** [comment]
thank you! :)

**Comment by flyboarder** [comment]
Still happening when keel is deployed via helm. How can I get polling from azure private registry?

**Comment by jamesla** [comment]
This appears to still be happening

**Comment by Silvenga** [comment]
Does anyone know why this is occuring?

**Comment by unixbird** [comment]
This is actually currently happening to me. Runs fine on 2 completely different nodes but a recently migrated one is getting this issue.
