### ISSUE TITLE
slack approvals don't come in helm3

### ISSUE THREAD

**Issue by botzill** [keel-hq/keel#528]
I installed the latest version `0.17.0-rc1` and also switched to `helm3` but seems that I don't get any slack notification when I submit new change via `native` webhook. Was there any changes on this parts?

**Comment by botzill** [comment]
OK, I will look into:

```
HelmDriver:       os.Getenv("HELM_DRIVER"),
        KubeContext:      os.Getenv("HELM_KUBECONTEXT"),
        KubeToken:        os.Getenv("HELM_KUBETOKEN"),
```

maybe we need to set them as well.

Would be great to have some info in docs about how to setup helm3

**Comment by rusenask** [comment]
might be something else, for me with helm3 I didn't have to set any other variables :|

**Comment by botzill** [comment]
I use custom helm driver to save data into postgress, do we need to setup that env `HELM_DRIVER_SQL_CONNECTION_STRING` 

?

**Comment by botzill** [comment]
@rusenask what helm driver you are using for helm3 that works for you?

**Comment by rusenask** [comment]
I don't think I have set anything specific so I guess the default one? maybe @nnt1054 can answer this?

**Comment by nnt1054** [comment]
Hey! Sorry for the lack of documentation, this wasn't a feature I've personally tested yet.  I'm having a look rn, the Helm3 provider uses this function from the Helm v3 Go pkg: https://github.com/helm/helm/blob/0ad800ef43d3b826f31a5ad8dfbb4fe05d143688/pkg/action/action.go#L359

It looks like you need to set both `HELM_DRIVER` to "sql" and `HELM_DRIVER_SQL_CONNECTION_STRING` just in your environment.  Lmk if that helps or what kind of results you're getting.

**Comment by botzill** [comment]
OK, I think we need to modify keel helm chart to accept custom env.

**Comment by botzill** [comment]
@rusenask if you can take a look and merge the chart so that I can easily test that.

Thx.

**Comment by botzill** [comment]
Hm, according to [docs](https://helm.sh/docs/helm/helm/):

```
$HELM_DRIVER | set the backend storage driver. Values are: configmap, secret, memory, postgres
```

I do set it to `postgres` or `sql` and I get the error:

```
panic: Unknown driver in HELM_DRIVER: postgres

goroutine 71 [running]:
helm.sh/helm/v3/pkg/action.(*Configuration).Init(0xc000015900, 0x25ba680, 0xc000022dc0, 0x0, 0x0, 0xc00005602c, 0x8, 0x2214e38, 0xc000026068, 0x32)
	/go/pkg/mod/helm.sh/helm/v3@v3.1.2/pkg/action/action.go:248 +0x4eb
github.com/keel-hq/keel/provider/helm3.(*Helm3Implementer).generateConfig(0xc000015580, 0x0, 0x0, 0x1dadf20)
	/go/src/github.com/keel-hq/keel/provider/helm3/implementer.go:102 +0x132
github.com/keel-hq/keel/provider/helm3.(*Helm3Implementer).ListReleases(0xc000015580, 0x35eb240, 0xc00071b480, 0x1, 0x0, 0x4e4221)
	/go/src/github.com/keel-hq/keel/provider/helm3/implementer.go:52 +0x4b
github.com/keel-hq/keel/provider/helm3.(*Provider).TrackedImages(0xc0000155c0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/keel-hq/keel/provider/helm3/helm3.go:181 +0x4b
github.com/keel-hq/keel/provider.(*DefaultProviders).TrackedImages(0xc0005f7080, 0xc000a1c198, 0x203000, 0x0, 0x0, 0x203000)
	/go/src/github.com/keel-hq/keel/provider/provider.go:101 +0x105
github.com/keel-hq/keel/trigger/poll.(*DefaultManager).scan(0xc0000156c0, 0x25b9cc0, 0xc00074f840, 0x1, 0x1)
	/go/src/github.com/keel-hq/keel/trigger/poll/manager.go:74 +0x4b
github.com/keel-hq/keel/trigger/poll.(*DefaultManager).Start(0xc0000156c0, 0x25b9cc0, 0xc00074f840, 0x0, 0x0)
	/go/src/github.com/keel-hq/keel/trigger/poll/manager.go:48 +0x102
created by main.setupTriggers
	/go/src/github.com/keel-hq/keel/cmd/keel/main.go:458 +0x759
```

@nnt1054 is that lib uptodate?

**Comment by botzill** [comment]
OK, the version that is used does not have yet `sql` driver implemented, https://github.com/helm/helm/blob/v3.1.2/pkg/action/action.go.

Can we upgrade it?

**Comment by nnt1054** [comment]
IIRC there were dependency issues with using the most recent Helm 3 Go pkg with (I think) the Helm 2 and k8s apis packages.  If someone doesn't get to it first, I'll look into trying to upgrade it again when I get the chance.  Moving forward we might want a new version of keel that supports Helm v3 only.

**Comment by rusenask** [comment]
I think it's totally fine to deprecate helm v2 with tiller, there aren't really any benefits anymore for people to continue using helm v2

**Comment by botzill** [comment]
I agree that sooner or later we need to migrate to helm3 and if dropping the support for v2 will make this transition faster.

**Comment by rusenask** [comment]
actually with go modules we can import any specific version without them clashing together. I am going on holiday in a few days so I will have a bit more spare time, I will try to debug this. If possible, we can keep v2 in, otherwise we will just have to support only v3.

**Comment by botzill** [comment]
Great. @rusenask let us know if you have any updates on that.

**Comment by botzill** [comment]
Hi.

Are there any updates on this?

**Comment by rusenask** [comment]
Hi @botzill, yeah, started working on this yesterday. As expected - a k8s dependency hell :)

**Comment by botzill** [comment]
Hi @rusenask 

Just wandering if you have any updates on the helm3 support?

**Comment by botzill** [comment]
Hi @rusenask, wandering if managed to make some progress on this.

Thx.

**Comment by botzill** [comment]
Hi.

Wondering if there is any update on helm 3 support for this issue?

**Comment by botzill** [comment]
hi @rusenask, again me :). wondering if you made any progress on this issue :).

Thx1

**Comment by rusenask** [comment]
hey @botzill, I think at this point I have even more work than I had previously.. :D good news - one of the projects is using helm3 so I will need to get this working for myself. My time currently mostly goes to https://grid.ai and https://docs.synpse.net/ so not much is left for other things : |

**Comment by botzill** [comment]
thx @rusenask for the update. 

Interesting services you work on will definitely check them.

**Comment by botzill** [comment]
hi @rusenask :)

How it's going?

Any change to look at this feature? 

Thx
