### ISSUE TITLE
Unable to poll images from Digital Ocean Container Registry

### ISSUE THREAD

**Issue by becash143** [keel-hq/keel#625]
Secrets are in place and able to pull images from DO container Registry. However, keel is unable to poll images from DO registry.
Error:
``time="2021-06-23T06:56:48Z" level=info msg=started context=buffer
time="2021-06-23T06:56:53Z" level=error msg="provider.defaultProviders: failed to get tracked images" error="context deadline exceeded" provider=helm
time="2021-06-23T06:57:01Z" level=error msg="provider.defaultProviders: failed to get tracked images" error="context deadline exceeded" provider=helm
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1515bb0]

goroutine 46 [running]:
github.com/keel-hq/keel/trigger/poll.(*RepositoryWatcher).addJob(0xc00062a720, 0xc0005237a0, 0xc0009160c0, 0x9, 0x2fd8700, 0xc000916f00)
	/go/src/github.com/keel-hq/keel/trigger/poll/watcher.go:245 +0x4b0
github.com/keel-hq/keel/trigger/poll.(*RepositoryWatcher).watch(0xc00062a720, 0xc0005237a0, 0x0, 0x0, 0x6000104, 0x0)
	/go/src/github.com/keel-hq/keel/trigger/poll/watcher.go:192 +0x8de
github.com/keel-hq/keel/trigger/poll.(*RepositoryWatcher).Watch(0xc00062a720, 0xc00093aee0, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/keel-hq/keel/trigger/poll/watcher.go:134 +0xf2
github.com/keel-hq/keel/trigger/poll.(*DefaultManager).scan(0xc0002a1fc0, 0x1ffe780, 0xc00039ef40, 0x1, 0x1)
	/go/src/github.com/keel-hq/keel/trigger/poll/manager.go:79 +0x78
github.com/keel-hq/keel/trigger/poll.(*DefaultManager).Start(0xc0002a1fc0, 0x1ffe780, 0xc00039ef40, 0x0, 0x0)
	/go/src/github.com/keel-hq/keel/trigger/poll/manager.go:63 +0x234
created by main.setupTriggers
	/go/src/github.com/keel-hq/keel/cmd/keel/main.go:437 +0x6eb

**Comment by mdtusz** [comment]
I'm seeing the same sorts of errors trying to poll from an azure container registry (which can be succesfully accessed when manually running `kubectl apply` with a deployment).

**Comment by craustin** [comment]
I'm getting the same SIGSEGV w/ keel 0.16.1. i'm using the standard kubernetes provider (not helm) and I get this error in Keel logs when I have a Keel-tracked k8s deployment that is trying to refresh itself with an image that doesn't exist in our image registry (due to an errant `helm upgrade`.) I can resolve it by doing another `helm upgrade` to get the deployment back to a good state. Maybe a Keel issue with error handling around missing images in remote image registries in-general?

**Comment by blakebarnett** [comment]
Also seeing this. I have a single deployment annotated, the images exist, but it's in a JFrog artifactory container registry. Unable to get it working using polling at all. I'll look into adding the registry Webhook support.
